org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties

minecraft_version=1.21.4
fabric_version=0.119.0+1.21.4
loader_version=0.16.10

parchment_date=2025.03.16

## Mod Properties

mod_id=lolmlmv
mod_name=More Loom Variants
mod_comp_name=MoreLoomVariants
mod_license=CC-BY-NC-SA-4.0
mod_version=1.2.2
mod_group_id=de.pnku.mlmv
mod_authors=pnku, LieOnLion
mod_description=Adding loom variants to Minecraft

# Quad Properties
quad_version=1.2.0