org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Minecraft Properties
minecraft_version = 26.1
minecraft_version_supported = [26.1,26.1.1]
minecraft_version_lower = 1.21.11
minecraft_version_upper =

# File Name
minecraft_version_name = 26.1
archives_base_name = MoreLoomVariants

## Mod Properties

mod_id=lolmlmv
mod_name=More Loom Variants
mod_name_short=More Loom Variants
mod_license=CC-BY-NC-SA-4.0
mod_version=1.2.2
mod_group_id=de.pnku.mlmv
mod_description=Adding loom variants to Minecraft

# Quad Properties
quad_version=1.2.0